default_platform(:ios)

platform :ios do

  lane :build_only do
    xcodebuild(
      scheme: "MatchPulse",
      project: "MatchPulse.xcodeproj",
      destination: "generic/platform=iOS Simulator",
      build_settings: {
        "CODE_SIGNING_ALLOWED" => "NO",
        "CODE_SIGN_IDENTITY" => "",
        "CODE_SIGNING_REQUIRED" => "NO"
      }
    )
  end

  lane :firebase do
    setup_ci

    build_app(
      scheme: "MatchPulse",
      project: "MatchPulse.xcodeproj",
      export_method: "ad-hoc",
      output_directory: "./build",
      output_name: "MatchPulse.ipa",
      xcargs: "CODE_SIGN_STYLE=Automatic DEVELOPMENT_TEAM=#{ENV['APPLE_TEAM_ID']}"
    )

    firebase_app_distribution(
      app: "1:981198068719:ios:e418854ab4273d90fbf41a",
      testers: "priyaparthiban702@gmail.com",
      release_notes: "Build #{ENV['GITHUB_RUN_NUMBER']} - #{ENV['GITHUB_SHA'][0..6]}",
      service_credentials_json_data: ENV["FIREBASE_SERVICE_ACCOUNT_JSON"],
      ipa_path: "./build/MatchPulse.ipa"
    )
  end

end
